### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by shlbatra** [aashimag175/RepoSQL-101#1]
Create a Readme file explaining how you set up the database in AWS

**Comment by aashimag175** [comment]
**AWS Database Setup Guide**

This guide provides step-by-step instructions on how to set up a MySQL database in Amazon Web Services (AWS). By following these steps, you'll be able to create a secure and scalable database for your application.

**Prerequisites**

Make sure you have the following:

- An AWS account.
- AWS Command Line Interface (CLI) installed and configured with necessary

**Steps**

**1. Log in to AWS Console:** Open your web browser and go to the [AWS Management Console (https://aws.amazon.com/).Sign in to your AWS account.

**2. Navigate to the RDS Dashboard** and select "Amazon RDS."

 **3. Create a New RDS Instance:** Click on "Create database" to create a new RDS instance.
 and choose the "Standard Create" option.

 **4. Choose Engine and Settings:** Choose the database engine you want to use (e.g., MySQL,MariaDB,).By selecting the appropriate version and configure the settings, including DB instance class, storage, and database details.

 **5. Configure Advanced Settings**: Set up your VPC, subnet group, and security group.Ensure that your database is securely accessible.Configure the database's username and password.

 **6. Create Database**: Click "Create database" to initiate the creation process.

 **7. Monitor Database Creation**: Monitor the progress in the RDS dashboard.

 **8. Connect to Your Database**: Once the database is available, you can connect to it using your preferred MySQL client.Locate the endpoint URL in the RDS dashboard to use for connecting i.e., **Host and Port, both**

Once you've successfully set up a MySQL database in AWS using Amazon RDS by ensuring that all the practices has been considered for security, backup, and maintenance to keep your database reliable and secure.
